server:
  port: 8082
  error:
    include-message: always

info:
  application:
    name: laugh-lounge
    author: Michael Ricahrds
    descriptions: A site to relax and share funny photos and text with your friends

spring:
  profiles:
    active: dev